from . import views
from django.urls import path
from .views import *


urlpatterns=[
    path('createresume',views.resume,name='resume'),
    path('createcompany',views.company,name='company'),
    path('contactus',views.contact,name='contact'),
    path('login2',views.login,name='login'),
    path('edit-seeker',views.editseeker,name='editseeker'),
    path('view-seeker',views.viewprofile_seeker),
    path('alljobs',views.alljobs,name='alljobs'),
    path('',views.home_view,name='home_view'),
    path('single/<int:jid>/<int:category>/',views.single_job_view,name='single_job_view'),
    path('category/<int:id>/', views.jobs_by_category,name='jobs_by_category'),
    path('categor/<int:id>/', views.category,name='category'),
    path('companyview',views.company_job_view,name='company_job_view'),
    path('apply/<int:jid>',views.apply,name='apply'),
    path('applied',views.appliedjobs,name='appliedjobs'),
    path('singlee/<int:jid>',views.single_job_view_seeker,name='single_job_view_seeker'),
    path('deleteapplication/<int:id>/',views.deleteappliedjob,name='deleteappliedjob'),
    path('alljobs-seeker',views.alljobs_seeker,name='alljobs_seeker'),
    path('logout/', views.logout_view, name='logout'),
    path('search-jobs',views.search_seeker),
    path('get_suggestions/', get_suggestions, name='get_suggestions'),
    path('search/', views.search_results, name='search_results'),
    path('search_seeker', views.search_results_seeker, name='search_results_seeker'),
    path('change_seeker',views.changepassword_seeker),
    path('app_status',views.application_status),
    path('singleee/<int:jid>',views.single_job_view_provider,name='single_job_view_provider'),
    path('deletejob/<int:jid>/',views.deletejob),
    path('managejob',views.managejobs),
    path('postedjob',views.postedjobs),
    path('managee/<int:jid>',views.manage_job_view_provider,name='manage_job_view_provider'),
    path('change/<int:jid>/',views.changeapplicationstatus),
    path('start/<int:jid>/',views.startapplicationstatus),
    path('view-provider',views.viewprofile_provider),
    path('view_deatails/<int:pid>/',views.viewcompanydeatils),
    path('viewapplicants/<int:jid>/',views.viewappicants),
    path('applicantdetails/<int:sid>/',views.viewapplicantdetails),
    path('select/<int:sid>/',views.selectcandidate),
    path('reject/<int:sid>/',views.rejectcandidate),
    path('selectedcandidate',views.selectedcandidates),
    path('postjob',views.post_job),
    path('view_license/<int:provider_id>/', views.view_license, name='view_license'),
    path('edit-provider',views.editprovider),
    path('changep_provider',views.changepassword_provider),
    path('alltesti',views.viewalltestimonials),
    path('addreview',views.add_review),
    path('thankyou',views.thankyou),
    path('addreview_pro',views.add_review_provider),
    path('resume/download/<str:sid>/', resume_download, name='resume_download'),

 ]