# Generated by Django 4.1.5 on 2023-04-13 03:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(default=0, verbose_name='User ID')),
                ('name', models.CharField(blank=True, default=0, max_length=25, verbose_name='User Name')),
                ('pid', models.IntegerField(default=0, verbose_name='Comapany Id')),
                ('cname', models.CharField(default=0, max_length=25)),
                ('jid', models.IntegerField()),
                ('title', models.CharField(default=0, max_length=25)),
                ('type', models.CharField(default=0, max_length=25)),
                ('email', models.EmailField(default=0, max_length=254)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='NOT SELECTED', max_length=25)),
            ],
            options={
                'verbose_name': 'View Applicant Detail',
            },
        ),
        migrations.CreateModel(
            name='Job_Providers',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=25, verbose_name='Company')),
                ('ceo', models.CharField(max_length=15, verbose_name='CEO Name')),
                ('tagline', models.CharField(max_length=25, verbose_name='Company Tagline')),
                ('category', models.CharField(max_length=25, verbose_name='Company Category')),
                ('des', models.CharField(max_length=250, verbose_name='Company Description')),
                ('phone', models.IntegerField(verbose_name='Company Phone Number')),
                ('website', models.CharField(max_length=30, verbose_name='Company Website')),
                ('empno', models.IntegerField(verbose_name='No Of Employees')),
                ('started', models.DateField(verbose_name='Started Rate')),
                ('photo', models.ImageField(upload_to='company/', verbose_name='Company Image in jpg/png Format')),
                ('license', models.FileField(upload_to='license/', verbose_name='Company Licence in pdf Format')),
                ('status', models.CharField(default='Not Verified', max_length=20, verbose_name='Current Status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Verify Company Profile',
            },
        ),
        migrations.CreateModel(
            name='Job_Seekers',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='Your Name')),
                ('address', models.CharField(max_length=200, verbose_name='Your Address')),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='Date Of Birth')),
                ('contact', models.IntegerField(verbose_name='Phone Number')),
                ('photo', models.ImageField(upload_to='seekers/', verbose_name='Your Image in jpg/png Format')),
                ('resume', models.FileField(upload_to='resume/')),
                ('skill', models.CharField(blank=True, max_length=80, verbose_name='Skills')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'View Job Seeker Profile',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'View Testimonial',
            },
        ),
        migrations.CreateModel(
            name='Post_Job',
            fields=[
                ('jid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Job Title')),
                ('type', models.CharField(max_length=50, verbose_name='Job Type')),
                ('location', models.CharField(max_length=50, verbose_name='Job Location')),
                ('des', models.CharField(max_length=500, verbose_name='Job Description')),
                ('reqirement', models.CharField(max_length=30, verbose_name='Job Requirements')),
                ('pid', models.CharField(default=1, max_length=50, verbose_name='Company Id')),
                ('status', models.CharField(default='Open', max_length=25)),
                ('category', models.CharField(default='Not Selected', max_length=25)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('salary', models.TextField(default='NOT DISCLOSED', verbose_name='Salary Package')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekera.job_providers')),
            ],
            options={
                'verbose_name': 'View Posted Job',
            },
        ),
    ]
