# Generated by Django 4.1.5 on 2023-04-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekera', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
