# Generated by Django 4.1.5 on 2023-04-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekera', '0002_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'View Testimonial',
            },
        ),
    ]
