# Generated by Django 4.1.5 on 2023-04-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekera', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
