# Generated by Django 4.2 on 2023-04-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekera', '0005_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AlterField(
            model_name='apply',
            name='cname',
            field=models.CharField(default=0, max_length=25, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(default='NOT SELECTED', max_length=25, verbose_name='Application Status'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='title',
            field=models.CharField(default=0, max_length=25, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='job_providers',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verification Status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekera.job_seekers'),
        ),
    ]
