# Generated by Django 4.2 on 2023-04-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekera', '0007_remove_review_user_review_provider_review_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='seekera.job_providers'),
        ),
        migrations.AlterField(
            model_name='review',
            name='seeker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='seekera.job_seekers'),
        ),
    ]
