# Generated by Django 4.2 on 2023-04-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekera', '0009_remove_review_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
