# Generated by Django 4.2 on 2023-04-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekera', '0010_review_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'verbose_name': 'View\u2008Applicant Detail'},
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Review,grde'),
        ),
    ]
