# Generated by Django 4.2 on 2023-04-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekera', '0011_alter_apply_options_review_stars_alter_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cname',
            field=models.CharField(default=0, max_length=55, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(blank=True, default=0, max_length=55, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='title',
            field=models.CharField(default=0, max_length=55, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='type',
            field=models.CharField(default=0, max_length=55),
        ),
        migrations.AlterField(
            model_name='job_providers',
            name='ceo',
            field=models.CharField(max_length=50, verbose_name='CEO Name'),
        ),
        migrations.AlterField(
            model_name='job_providers',
            name='cname',
            field=models.CharField(max_length=50, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='job_providers',
            name='des',
            field=models.CharField(max_length=500, verbose_name='Company Description'),
        ),
        migrations.AlterField(
            model_name='job_providers',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='job_providers',
            name='tagline',
            field=models.CharField(max_length=100, verbose_name='Company Tagline'),
        ),
        migrations.AlterField(
            model_name='job_providers',
            name='website',
            field=models.CharField(max_length=100, verbose_name='Company Website'),
        ),
        migrations.AlterField(
            model_name='job_seekers',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Your Address'),
        ),
        migrations.AlterField(
            model_name='job_seekers',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Your Name'),
        ),
        migrations.AlterField(
            model_name='job_seekers',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='job_seekers',
            name='skill',
            field=models.CharField(blank=True, max_length=150, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='reqirement',
            field=models.CharField(max_length=300, verbose_name='Job Requirements'),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='title',
            field=models.CharField(max_length=75, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='type',
            field=models.CharField(max_length=60, verbose_name='Job Type'),
        ),
    ]
