# Generated by Django 4.2 on 2023-04-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekera', '0012_alter_apply_cname_alter_apply_name_alter_apply_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_providers',
            name='usertype',
            field=models.CharField(default='Provider', max_length=20),
        ),
        migrations.AddField(
            model_name='job_seekers',
            name='usertype',
            field=models.CharField(default='Seeker', max_length=20),
        ),
    ]
