# Generated by Django 4.2 on 2023-04-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekera', '0016_review_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Review'),
        ),
    ]
